{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vioplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vioplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vioplot/vioplot_{{ version }}.tar.gz
  sha256: c3b910327fa9c07194400439817b87192ae16e997cbf5eccb8f001d966478f00

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-sm
    - r-zoo
  run:
    - r-base
    - r-sm
    - r-zoo

test:
  commands:
    - $R -e "library('vioplot')"           # [not win]
    - "\"%R%\" -e \"library('vioplot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=vioplot
  license: BSD-3-Clause
  summary: 'A violin plot is a combination of a box plot and a kernel density plot. This package allows extensive customisation of violin plots. '
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - rasmusagren

# Package: vioplot
# Title: Violin Plot
# Version: 0.3.0
# Author: Daniel Adler <dadler@uni-goettingen.de>
# Maintainer: Tom Kelly <tom.kelly@postgrad.otago.ac.nz>
# Description: A violin plot is a combination of a box plot and a kernel density plot. This package allows extensive customisation of violin plots.
# Depends: sm, zoo
# License: BSD_3_clause + file LICENSE
# LazyData: true
# RoxygenNote: 6.1.1
# Suggests: knitr, rmarkdown, testthat
# Language: en-GB
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-01-09 08:33:14 UTC; tom
# Repository: CRAN
# Date/Publication: 2019-01-25 14:50:02 UTC
