travis:
  secure:
    BINSTAR_TOKEN: KvSOtj0C3M5D0WgK5LPr7zsU0aaLdWSq2MiHZv5d2HHJyayjtbtQEe7iP1yDeWUxWhQ8QvZpC0GTEchSZGDIk4MGs6/n4D6mxx6kbZLwoqlmtguOzWVfh4y0w3O9sBGMTsMgX9pFTcPOsigg2ZlZ7aOg7lsjYR4+PAxJ5j5777UCo8klzsI0K4sTkdzsvy0MXkmE5DJYB5JUvExQ0krl4W1aQZ7diksWqgiaMKYXoFf/U6UfnYrWcIsB9qsBXQNKiAJPVDoCQJAemjyezMHmtlGXwSo/GR4HIiLx6wjoyZtqqt78ac47X8MEroOGnAm9CS5YMvjt8Gj2tGr8P6R87yzcHYjUrSERR56iC95ulaGaBPa1N0KQljOE9xL2OVjOw1DkonVYIBIhJDhSSqY93Privge4lrv1jiyMrKy7RCN1sbcBtDt869rt+1SN2GmuyD/Mli3pq8vbGYyzQkjI0NBsZOo15sEInxtl/6sFdE9kbvtnrAfDbSjORUn5Wgn9NYkEHSNNlL8wgvCRBhYFdZpWzhxibC4YhZ/M0+XSV+XAq1w/DpLDAY9KK6aC5P8sozMgghPKC/NFCei1viBvpUUyrI+BblQCJAaJAX4gcpxY/rY0bDhB2UkNb+0hTQpcM1O+chhWp5r6Jc/576d6DW+4H4wkLtvB1bMnB4fI3kw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
