travis:
  secure:
    BINSTAR_TOKEN: hcpTZnRNcadbYe1L9XZJbM1vNJx6cPcjo84yPHLnI+XjQhrxkgVPhlX7PEPerG09z132ybRnpjUVFC5RfJBvw6RhnKb5MWOdbVUCbt7o+EtX5ImIF21CBy5BCbA+xvT5IbbOxv/c7QftaQnse2LKy+7QIv+yC05As+L1cV1KwC91rE69DIdhEBNL6ravUuD53CeIeJ+ItesGgEP6vSUi52Dsh7D14HyVlqdtHtYNBj30OiRHnmqHRMZkZSJmH0nfJXYCB5lvs8+PsX6XwxCcpS/uCIMqeqCkPmGMyT5ma182B6rZsNBOR9D9AcN4+6URArUk9g0N9Z5GAEpG8rK5Dw1ks63kB7aGMpN5hGsUTe1lqqchxmrI05KE2+mHOenAtj84piyoHuXjn7HONVYRktuydmnvXnHUa6fB8rqX/1iupKYj+mIbZ4zpW4NeSJ5bDc2bYND5SiOj4Nomnr67wl5a6U9nvTjZTZpkuNBgr30N7D5rFQqPuIjWum7Jr1ChobO463DgIxYimcv4Kbc+FMpQ6DihlYg74Ez2q2jOZPM5STZcamyOIx3gQwHv3VvC09CR77dAJsFoFmTgOEqjvpboHxInsdv41CcPLgQNooRSZMY6CiyVLyTUAI5if/iSoyrM33NVuBGVhp93UqyjE7qJG4Mh4cNjevKwzHbWGEA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
