travis:
  secure:
    BINSTAR_TOKEN: G/BBiwduKkc3nZTLNdfhlK3vPA8NpNOh9LfOiDPjc3s583CKIsO9214rMd4s2XJkj1EDBpJzhU1Pa8TWARezMqoJU1M8hltGPpgRm4aNxyBerk22PuXhosNkKl927UitosRaw/aOxLDWw+ozg1YF71VbtY1Yc65v8maHcAR6VEuUUHp91MmRQ/iKbbEm9VWttbv8gT7DbmIPUkCkUxHPQVBMndXLzUQb/XyWF/RwM143/AsUrBBntUu/IA8M145N8HB20BWMFdHRq1OxcIYFKCt1gX5UO9+ND8MgIbsEMlTq34XNPXFUmdehshdy2CxpJjwqKakx8utDJVAotJMmbaxFxCJsWEz0t3qzBLqDqUwBCv+eQGJBtXHNLRMb1wdHyFM85mrqOimWPKNPnnuRcbMVy8uajy67JEjyUibv+nWESs3Tx77f29b3ZDoEI+V8TsnMegQUMYB+xSLGbe/XwVqJv0YU8dZPKqOG0yEPj96C2h5iBT0y4aIPWBTxzsg3TQ71hRPOCb9tpLNrnr+UQSgC1HgJKryZ6Sa+6rf8V4pDPGE/BWys2k0RaiiCpHDFEFGD/ObkulcEmsbPKwNtSZNBsq+5rET7a/XiJFzwUulO+3Ww4xGVWCTTApVpBg1nQb4OpvTF18vUeZB5mC8GVP4wumdSB0A8g3ulh4yXkpM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
